export const routes = {
  auth: '/auth',
  changePassword: '/change-password',
  adminDashboard: '/dashboard/admin',
  adminKpis: '/dashboard/admin/kpis',
  adminKpiDetail: '/dashboard/admin/kpis/:id',
  adminCreateKpi: '/dashboard/admin/kpis/create',
  adminEditKpi: '/dashboard/admin/kpis/:id/edit',
  adminOrganizations: '/dashboard/admin/organizations',
  adminUsers: '/dashboard/admin/users',
  adminCommittees: '/dashboard/admin/committees',
  adminAlerts: '/dashboard/admin/alerts',
  adminReports: '/dashboard/admin/reports',
  staffDashboard: '/dashboard/staff',
  staffNotifications: '/dashboard/staff/notifications',
  staffSubmitKpi: '/dashboard/staff/submit-kpi',
  staffSubmissionHistory: '/dashboard/staff/submission-history',
  staffKpiDetail: '/dashboard/staff/kpis/:id',
  tbiManagerDashboard: '/dashboard/tbi_manager',
  tbiManagerNotifications: '/dashboard/tbi_manager/notifications',
  tbiManagerSubmitKpi: '/dashboard/tbi_manager/submit-kpi',
  tbiManagerSubmissionHistory: '/dashboard/tbi_manager/submission-history',
  tbiManagerKpiDetail: '/dashboard/tbi_manager/kpis/:id',
} as const;
